### ISSUE TITLE
Handle 404 server code response

### ISSUE THREAD

**Issue by mxgnr** [enten/angular-universal#19] opened 2018-09-18 09:49 UTC
Hi there,

Thank you @enten for this very useful starter kit !

I'm currently trying to set my app to be able to send a 404 server code response when a visited route is not available. I've found a few tutorials for Angular Universal ([here](https://blog.thecodecampus.de/angular-universal-handle-404-set-status-codes/), [this one](https://skynix.company/blog/solutions/how-to-set-404-status-code-in-angular/) or even [here](https://blog.lysender.com/2018/07/angular-6-x-404-page-with-correct-header-using-angular-universal/)) but each time the server file script is quite different from this project, i've been trying to make it work for a couple hours without success. 

Can you describe how implement this functionnality into this starter kit ? 

Thanks

**Comment by enten** [comment] 2018-09-21 10:44
The simple way to achieve that:

* add the router module ;
* add a component to handle not found routes ;
* inject [REQUEST token from `@nguniversal/express-engine`](https://github.com/angular/universal/blob/v6.1.0/modules/express-engine/tokens/tokens.ts#L11) in your error handler component ;
* use request instance to set status code 404.

Gotcha: the request injection should be optional because it will be underfined in browser bundle/side.

I will write an example soon to illustrate this usecase.

**Comment by mxgnr** [comment] 2018-09-21 14:50
I would like an example indeed, since i can't make it work either with RESPONSE or REQUEST token, as you describe above.

I've seen output errors in my console about dependencies which seems to be only for server purpose (like express), maybe angular-cli related ? It seems to be similar to [this issue](https://github.com/angular/angular-cli/issues/11130).

**Comment by enten** [comment] 2018-09-21 16:27
@maxgranier  
I will write that example this weekend.

About the issue that you linked: do you think that you encountered that issue?
Have you a repository which reproduce this issue?

**Comment by mxgnr** [comment] 2018-09-24 09:22
Hi,

This is what i tried so far : 

```typescript
import { Component, OnInit, Optional, PLATFORM_ID, APP_ID, Inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { RESPONSE } from '@nguniversal/express-engine/tokens';
import { Response } from 'express';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.less']
})
export class NotFoundComponent implements OnInit {

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    @Inject(APP_ID) private appId: string,
    @Optional() @Inject(RESPONSE) private response: Response
  ) { }

  ngOnInit() {
    if (!isPlatformBrowser(this.platformId)) {
      this.response.status(404);
    }
  }
}
```

And i got this output errors from the console :

```
[...]

WARNING in ./node_modules/express/lib/view.js
81:13-25 Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/cookie-signature/index.js
Module not found: Error: Can't resolve 'crypto' in '[...]/node_modules/cookie-signature'
ERROR in ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'crypto' in '[...]/node_modules/etag'
ERROR in ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in '[...]/node_modules/destroy'
ERROR in ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in '[...]/node_modules/etag'
ERROR in ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'fs' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'fs' in '[...]/node_modules/send'
ERROR in ./node_modules/send/node_modules/mime/mime.js
Module not found: Error: Can't resolve 'fs' in '[...]/node_modules/send/node_modules/mime'
ERROR in ./node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'http' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'http' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'http' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'net' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/content-disposition/index.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/content-disposition'
ERROR in ./node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/express/lib'
ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/mime-types'
ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/send'
ERROR in ./node_modules/send/node_modules/mime/mime.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/send/node_modules/mime'
ERROR in ./node_modules/serve-static/index.js
Module not found: Error: Can't resolve 'path' in '[...]/node_modules/serve-static'
ERROR in ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'stream' in '[...]/node_modules/destroy'
ERROR in ./node_modules/iconv-lite/lib/streams.js
Module not found: Error: Can't resolve 'stream' in '[...]/node_modules/iconv-lite/lib'
ERROR in ./node_modules/iconv-lite/lib/extend-node.js
Module not found: Error: Can't resolve 'stream' in '[...]/node_modules/iconv-lite/lib'
ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'stream' in '[...]/node_modules/send'
ERROR in ./node_modules/body-parser/lib/read.js
Module not found: Error: Can't resolve 'zlib' in '[...]/node_modules/body-parser/lib'
Child: server
  Date: 2018-09-24T09:17:44.760Z
  Hash: 4d6f0c0353c3c7e9a4c6
  Time: 228ms

ERROR in [udk] compilation cancelled due to errors in previous compilers: browser
```

It seems to happen when i try to inject Response from express.

**Comment by enten** [comment] 2018-09-24 19:27
@maxgranier  
Firstly: commit 365497b7 which implement a dummy not found component which set response status 404.

Below some information which can help to fix your issue.

In the [commit](365497b7), we use NotFoundComponent when browser hit special route `**`.
The component use [RESPONSE](https://github.com/angular/universal/blob/v6.1.0/modules/express-engine/tokens/tokens.ts#L12) to set status 404.

**[The most important part on the server side](https://github.com/enten/angular-universal/commit/365497b7910fe34f97693a2d0b4a89deacfb5898#diff-45ec1a2ac33cf965ab5afde0254bd928R18) is to provide [RenderOptions `req` and `res`](https://github.com/angular/universal/blob/v6.1.0/modules/express-engine/src/main.ts#L33) when your render the template**:

```ts
api.get('*', (req, res) => res.render('index', { req, res }));
```

**The second important part is to design your angular project in an universal way**.
You can notice that our issue is relative to server stuff which can't be resolved in the browser bundle.
udk avoid server compilation (because there is an error in the browser bundle): but if you run `ng run yourproject:server` you will see that your server build well.

The `NotFoundComponent` should work in browser and server. To fix the error: we need to remove `express` import and use a partial response interface.

```ts
import { Component, OnInit, Optional, PLATFORM_ID, APP_ID, Inject } from '@angular/core';
import { isPlatformServer } from '@angular/common';
import { RESPONSE } from '@nguniversal/express-engine/tokens';

interface PartialResponse {
  status(code: number): this;
}

@Component({
  selector: 'app-not-found',
  template: '<h1>Page Not Found</h1>',
})
export class NotFoundComponent implements OnInit {
  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    @Inject(APP_ID) private appId: string,
    @Optional() @Inject(RESPONSE) private response: PartialResponse,
  ) { }

  ngOnInit() {
    if (isPlatformServer(this.platformId) && this.response) {
      this.response.status(404);
    }
  }
}
```

Of course, in real application, setting response status must be accomplish with a service.

```ts
@Injectable()
export class HttpContextService {
  constructor(
    @Optional() @Inject(REQUEST) readonly request: PartialRequest,
    @Optional() @Inject(RESPONSE) readonly response: PartialResponse,
  ) { }

  setStatusCode(code: number) {
    if (this.response) {
      this.response.status(code);
    }
  }
}
```

**Comment by mxgnr** [comment] 2018-09-26 09:37
Really helpful, thanks a lot, also for the explanation !

**Comment by enten** [comment] 2018-09-26 10:00
@maxgranier You're welcome. Can we close your issue?

**Comment by mxgnr** [comment] 2018-09-26 12:15
Sure no problem

**Closed as completed** 2018-09-26 12:20 UTC
Labels: enhancement
