### ISSUE TITLE
Problem with LazyLoading

### ISSUE THREAD

**Issue by Stivin** [enten/angular-universal#1] opened 2018-04-26 08:53 UTC
Greetings. Thanks for your work.

Bumped into a problem with Lazy Loading. For example, I create a lazy module "home". I register in routing:
`{ path: '', loadChildren: './home/home.module#HomeModule' },`

And I get after picking up the assembly:
> [HMR] Update check failed: SyntaxError: Unexpected token < in JSON at position 0

> Unhandled Promise rejection: Unexpected token < in JSON at position 0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: Unexpected token < in JSON at position 0

And with the new assembly we get:
> ERROR in ./src/app/ngmodule.ts
Module not found: Error: Can't resolve 'home/home.module.ngfactory.js' in '/var/www/universal-starter/src/app'

**Comment by enten** [comment] 2018-04-26 10:00
This issue is already known (angular/devkit#698) and fixed by the pull request angular/devkit#770.

The fix is available since [@ngtools/webpack](https://www.npmjs.com/package/@ngtools/webpack) v6.0.0-rc.6 (one day ago).

Try to install `npm install --save-dev @ngtools/webpack@^6.0.0-rc.6` and retry to build your project.

**Comment by Stivin** [comment] 2018-04-26 13:46
If you install: `npm install --save-dev @ngtools/webpack@^6.0.0-rc.6`
> Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.

If you update: `@angular-devkit/build-angular@0.5.8`
> TypeError: Cannot read property 'tsConfig' of undefined

**Comment by enten** [comment] 2018-04-26 14:42
Thanks for your feedback. **I will work on that issue as soon**.

Currently, if you really need to compile with lazy modules:
* downgrad dependencies (ngtools/webpack 6.0.0-rc.5 and angular-devkit/build-angular 0.5.7)
* manually apply [the patch to fix relative paths in module map imports](https://github.com/angular/devkit/pull/770/files#diff-a15bb80df72e2d6edf6699f8deca70d6) on `./node_modules/@ngtools/webpack/src/transformers/export_lazy_module_map.js`.

Note: don't use `git apply` because the patch work on typescript sources only, you must edit the code manually. If you encounter a problem to do that, I will send you the entire file with the patch applied.

**Comment by Stivin** [comment] 2018-04-26 14:52
Thank you. I'll try to do it. I will write about the results :)

**Comment by Stivin** [comment] 2018-04-26 15:37
Did as you wrote.When the page is loaded, when it has already appeared, it re-opens again and the console:
> Error: Cannot match any routes. URL Segment: 'a4ec67acae8345f663a2.hot-update.json'

**Comment by enten** [comment] 2018-04-26 16:25
The last error which you describe sounds like an HMR error due to an extreme server reloading:

* If you use the universal dev server (with `npm run dev` or `npx ng-udkc`)
* Do updates which triggered HMR
* The browser is notified of changes
* And after, if an update triggered an extreme server reloading: the dev container restarts and the server is fully rebuilds
* On browser side, when the server reloaded successfully, the [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) reconnects and requests hot chunks of the previous compilation
* That previous hot chunks was deleted when the dev container restart: so an error is throws.

If your issue is the same: you only needs to refresh your browser. In that way the browser _forget_ the previous hot chunks.

**Comment by Stivin** [comment] 2018-04-26 22:10
I really like how your build works. Still to the end to solve a problem with Lazy Loading :)
How does your project work?

**Comment by enten** [comment] 2018-04-27 05:56
I investigated this issue and I found the cause: [an enhancement to enable file replacement in ServerBuilder introduced in @angular-devkit/build-angular v0.5.8](https://github.com/angular/devkit/commit/c1ddbbfa5b1deac0b833d42c2c4bc2524b660980#diff-c3f2e42cc0031654b960b90c9f82e786).

That enhancement changed the [ServerBuilder.buildWebpackConfig\(\) method's signature](https://github.com/angular/devkit/commit/c1ddbbfa5b1deac0b833d42c2c4bc2524b660980#diff-c3f2e42cc0031654b960b90c9f82e786L106):

```ts
// @angular-devkit/build-angular v0.5.7
buildWebpackConfig(
  root: Path,
  projectRoot: Path,
  options: BuildWebpackServerSchema
)

// @angular-devkit/build-angular v0.5.8
buildWebpackConfig(
  root: Path,
  projectRoot: Path,
  host: host: virtualFs.Host<Stats>,
  options: BuildWebpackServerSchema
)
```

[That change breaks the UdkBuilder](https://github.com/enten/udk/blob/v0.3.9/angular/lib/udk-builder.js#L207): an architect command used to make the universal build. [I fixed UdkBuilder to be compatible with @angular-devkit/build-angular 0.5.8](https://github.com/enten/udk/commit/625ae65058eba386ec8aec93714f38fa314fe756).

**Now you can fix your build with lazy routing by installing @angular-devkit/build-angular ^0.5.8 and udk ^0.3.10.**

```shell
npm install --save-dev @angular-devkit/build-angular@~0.5.9 udk@~0.3.10
```

**Warning**: angular-devkit/build-angular v0.5.8 depends to ngtools/webpack v6.0.0-rc.6 which fixed the ServerBuilder with lazy modules. You don't need to install the good version of ngtools/webpack manually.  
When you try to build, If you have the error ``:

```shell
npm uninstall @ngtools/webpack
rm -fr node_modules
npm install --save-dev @angular-devkit/build-angular@~0.5.9 udk@~0.3.10
npm start
```

Is that updates fixing your issue with ServerBuilder and lazy routes?

**Comment by Stivin** [comment] 2018-04-27 08:57
when `npm start` all perfectly :). When I start `npm run dev` everything is fine, except for one moment.
![2018-04-27 11-47-16](https://user-images.githubusercontent.com/7903163/39353619-e603a5ae-4a10-11e8-888f-8f6ab71b4172.png)
Between the blue and red lines the content of the page is reloaded :( Can this be solved?

But when I do `npm run build:prod` and `node dist/app/server/main.js` everything is just fine :)
Thank you very much :)

**Comment by enten** [comment] 2018-04-27 10:31
The command `npm run build:prod` launch a build for production environment.  
The command `npm run dev` launch a build for development environment (inside a dev container).

Assets produced by each build aren't the same. In addition, the dev container dynamically add entry and plugins to enable HMR on browser and server sides.

I think that the reload have a link with the HMR on browser side. It's a common behavior that I have already encountered with an dev environment for universal react application.  
That behavior may be fixed. But is it really needed to the development environment?

I'm happy that you like the way which the build works. It's just a combination with the angular-devkit (and its architect toolchain) and [udk](https://github.com/enten/udk) (a webpack extension created to support universal development). I wrote an architect builder called [UdkBuilder](https://github.com/enten/udk/blob/master/angular/lib/udk-builder.js) to handle the target `ng run ng-universal:udk`. The universal development server is based on [udk dev container](https://github.com/enten/udk#dev-container).

My apologies for not giving more information in my answers (sadly I'm bad in english). But If you want to understand how udk works, you can [ask question by opening an issue](https://github.com/enten/udk/issues/new). The answers will be a base for a documentation.

**Comment by Stivin** [comment] 2018-04-27 11:27
Thanks for your reply. I think that this problem can be noted as an allowed :)

**Closed as completed** 2018-04-27 11:55 UTC
Labels: bug
