### ISSUE TITLE
Requires a dependency for production

### ISSUE THREAD

**Issue by Stivin** [enten/angular-universal#2] opened 2018-04-28 15:54 UTC
Good afternoon,

Faced with a problem. I started the assembly (prod): `npm run build:prod` and uploaded the application to the server. I got errors that dependencies are required (node_modules). In the application for production there should be no such :(

Thank you very much for your work.

**Comment by enten** [comment] 2018-04-28 16:06
**I think that node dependencies aren't installed on you production environment.**

Upload project's `package.json` and run `npm install --production` to install runtime dependencies.

[By defaults, the webpack config dynamically created by angular-cli for the server doesn't bundle any dependency \(except some angular's dependencies\)](https://github.com/angular/devkit/blob/v6.0.0-rc.5/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts#L27).

**Comment by Stivin** [comment] 2018-04-28 16:46
I think it's wrong to have separate dependencies in a fully prepared application. I used to make vendor.js in the server directory next to main.js. Then I was 100% sure that when I update the application on the server, it will work. And you do not need to check, install, reinstall dependencies.

What do you think?

**Comment by enten** [comment] 2018-04-29 10:40
I understand your needs and it's a good pattern to satisfy them.

Personally, that default behavior satisfied me than bundle all external dependencies:

* the build time is faster
* the build size is smaller
* the server startup time is faster / memory allocated when starting is smaller
* module resolution at runtime is natively handled by node.js
* let the `package-lock.json` guarantees version of dependencies

Of course, in some cases, we need to bundle certain dependencies required for runtime (ngx-bootstrap for example).

**Is your issue fixed by installing external dependencies?**

**Comment by Stivin** [comment] 2018-04-30 12:11
Thanks for your reply. You're right.
But dependencies are collected along the path /browser/main{hash}.js. Correctly? So, can we just go to this main{hash}.js and get all our dependencies without installing them on the server. 
Or I'm wrong? :)

**Comment by enten** [comment] 2018-05-01 10:18
**Right, if your issue is fixed: can we close that issue?**

The `/dist/app/browser` files are used to in the browser: it's the SPA version of the application. These files bundle the dependencies needed to the browser. The `/dist/app/server` files are used in the server: it's the SSR version of the application. These files doesn't bundle the dependencies because we can resolve them with the `node_modules` folder.

In universal web application development, we generally need to build 2 targets:

* `ng-universal:server`: this build is node.js server process which provide the server side rendering (SSR) of the web application at least and optionally an API to handle asynchronous actions (triggered by the application) ;
* `ng-universal:browser`: this build is the optimized to run on the browser - it handle the client side rendering (CSR) - and used externals API's to handle some asynchronous actions.

Ideally, the server API provide all routes needed by the asynchronous actions: that API contains secret keys to call others business micro-services. In that case, you need to create a system to proxify API call when it fired on browser: in that case, the call must be address to the server API which redirect it to the real business service: like that you never expose secrets in the browser.

That is a complex pattern (the pattern above) to implement and can potentially create performance issues (or _deadlocks_) if the server call the API in the same way as the browser do during the SSR process: the server recevies a request, it starts the SSR of the request, the SSR triggers an async action to the server API, the call is send to the server itself, and if the server can't handle more request, the API call won't never be handled.  
To prevent this kind of issue, we must to be responsive to implement services in an _universal way_ like [the universal data access layer for web applications \(Fetchr by Yahoo\)](https://github.com/yahoo/fetchr).

That is only one of the various challenges of the universal web application development. The universal rendering being the first, then the transfer of the application state, then the rehydration of the applcation in the browser (and prevent [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)), then the universal data access layer.

**Comment by Stivin** [comment] 2018-05-01 12:29
Many thanks for the detailed explanation. You can close this issue. I am grateful for your work

**Closed as completed** 2018-05-01 12:51 UTC
Labels: question

**Comment by enten** [comment] 2018-05-08 07:43
@Stivin  
**If you want to bundle all server dependencies**, you can set the [bundleDependencies](https://github.com/angular/devkit/blob/v6.0.0/packages/angular_devkit/build_angular/src/server/schema.json#L129) property (of the server target) to `"all"` (it's `"none" by defaults)`: so you won't need to install dependencies on server anymore.

```diff
// angular.json
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ng-universal": {
      "root": "",
      "projectType": "application",
      "prefix": "app",
      "architect": {
        // ...
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/app/ngmodule.ts",
            "tsConfig": "src/tsconfig.server.json",
+           "bundleDependencies": "all"
          },
          "configurations": {
            "production": {
            }
          }
        },
        // ...
      }
    }
  }
}
```

**Comment by Stivin** [comment] 2018-05-08 08:39
Nothing happened. Run `npm run build:prod` and without **node_modules** - **Cannot find module**

**Comment by enten** [comment] 2018-05-08 09:08
Dependencies are needed to build browser and server bundles.

By defaults:
* the browser bundle includes all dependencies ;
* the server bundle externals all dependencies ([except some exceptions](https://github.com/angular/devkit/blob/v6.0.0/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts#L26)).

You can include dependencies in the server target by set _bundleDependencies_ property to `"all"`.

Run `npm run build:prod` to create browser and server bundles in `dist/app` folder.
When it's done: every runtime's dependencies needed for browser and server bundles are included.

Now you can remove the `node_modules` folder and run `node dist/app/server/main.js` to see the universal angular web app running.

**Comment by Stivin** [comment] 2018-05-08 09:22
Добавил **"bundleDependencies": "all"**
```
"server": {
    "builder": "@angular-devkit/build-angular:server",
    "options": {
        "outputPath": "dist/server",
        "main": "src/app/ngmodule.ts",
        "tsConfig": "src/tsconfig.server.json",
        "bundleDependencies": "all"
    },
    "configurations": {
        "production": {}
    }
},
```
Run `npm run build:prod` and create `dist` folder (in my case inside: browser and server).
Inside the directory server: main.js and ngmodule.js files
Run `node ./dist/server/main.js` and and get an error message: `Cannot find module ...` :(

**Comment by enten** [comment] 2018-05-08 10:13
**I think it's specific to your repository.** Because when I clone the current repo enten/angular-universal, run `npm install`, set _bundleDependencies_ to `"all"`, run `npm run build:prod`, remove `node_modules` folder and run `node dist/app/server/main.js`: it's works as expected.

But may it can be a bug triggered by your code. We need to investigate. Can you share a repo which reproduced your issue?

**Comment by Stivin** [comment] 2018-05-08 10:31
Oh. Looked like it was not in that branch. I switched to the master and everything worked. Thank you very much :)
