### ISSUE TITLE
Can't run project after update to Angular 6.0.0

### ISSUE THREAD

**Issue by alexthelion** [enten/angular-universal#3] opened 2018-05-05 09:58 UTC
I'm getting error when I try to run 

> npm start

:

> module.js:538
>     throw err;
>     ^
> 
> Error: Cannot find module 'L:\ng-universal\$npm_package_main'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ng-universal@0.0.0 start: `node $npm_package_main`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ng-universal@0.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

This is my package json file:
```

{
  "name": "ng-universal",
  "version": "0.0.0",
  "license": "MIT",
  "main": "dist/app/server/main.js",
  "scripts": {
    "ng": "ng",
    "prestart": "npm run build:prod",
    "start": "node $npm_package_main",
    "build": "ng run ng-universal:udk",
    "build:prod": "ng run ng-universal:udk:production",
    "dev": "ng-udkc",
    "dev:spa": "ng serve --hmr",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "now-build": "ng run ng-universal:udk:production",
    "now-start": "node $npm_package_main"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "core-js": "^2.5.5",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.0",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@angularclass/hmr": "^2.1.3",
    "@types/jasmine": "~2.8.7",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.0.4",
    "@types/webpack-env": "^1.13.6",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.0.0",
    "protractor": "~5.3.1",
    "ts-node": "~6.0.2",
    "tslint": "~5.10.0",
    "typescript": "^2.7.2",
    "udk": "^0.3.10"
  }
}

```

**Comment by enten** [comment] 2018-05-06 15:55
I [updated angular dependencies to 6.0.0](https://github.com/enten/angular-universal/commit/b718acb4b9d185f33fa0e579737f17709a2ad9cb) and the repository seems still working.

I think the error `Error: Cannot find module 'L:\ng-universal$npm_package_main'` is thrown because npm not dynamically replace `$npm_package_main` by the `package.json` _main_ field.

I encountered this issue on a windows environment too. But I don't know if it's inherent to windows or a previous npm version (I don't investigate that issue yet because I don't have it on my main dev platform).

**You may fix this issue by update your `package.json` to avoid use of the dynamic reference `$npm_package_main`.**

```diff
-    "start": "node $npm_package_main",
+    "start": "node "dist/app/server/main.js",
```

**Comment by TheCraccer** [comment] 2018-05-21 10:40
Had the issue too. Replacing the main field worked

**Comment by enten** [comment] 2018-05-21 12:45
@TheCraccer Thanks to confirm the cause of this issue.

@alexthelion I closed this issue. But if you still have this issue, you can comment on this thread.

**Closed as completed by enten** 2018-05-21 12:45 UTC
Labels: question
